org: '1256177802'
app: chord-progression
stage: prod
component: koa
name: koa-vkkymr8qw
inputs:
  src:
    src: ./
    exclude:
      - .env
      - node_modules/**
  region: ap-guangzhou
  runtime: Nodejs10.15
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
    serviceTimeout: 60
    autoCreateDns: false
  isAutoCiDeploy: false
  functionConf:
    eip: true
    timeout: 3
    memorySize: 128
  layers:
    - name: '${output:${stage}:${app}:chord-progression-layer.name}'
      version: '${output:${stage}:${app}:chord-progression-layer.version}'
